### PR TITLE
Add support to pass http headers when running codegen cli

### PR DESCRIPTION
**Pull request by lorefnon**

### CODE REVIEW

**Review by timkendall — CHANGES_REQUESTED** [review]
Please utilize [Yargs](https://yargs.js.org/docs/) to do this CLI argument parsing. As always appreciate the contribution 👍

**Comment by lorefnon** [comment]
I don't believe yargs is flexible enough for this: 

As added [here](https://github.com/timkendall/tql/blob/d3ee04e529a5c2bda424f22458bf91edc7ab9199/docs/quickstart/codegen.md), this PR proposes two usages: 

```
You can also pass headers (eg. for authentication) to your graphql API endpoint if needed:

npx @timkendall/tql-gen http://api.example.com/graphql --headers.Authorization="Bearer 20394823423"

or

npx @timkendall/tql-gen http://api.example.com/graphql --headers="Authorization: Bearer 20394823423"

In either usage patterns, you can pass multiple headers by repeated usage of --headers
```

The first usage is what yargs can support out of the box. I also wanted to support the second usage because that is how headers are represented in http request. For supporting both (including repeated invocations) I had added that parsing logic. 

If you prefer I can only retain the first usage and simplify the parsing logic.

**Comment by timkendall** [comment]
Let's stick with the simpler parsing logic. I like the fancy version but it's likely going to be hard to port over to the Rust implementation of the CLI (unless one of their mature CLI arg libraries supports this format out of the box).

**Review by timkendall — APPROVED** [review]
On second thought who knows when I’ll get around to finishing the Rust version :) This is good. Thanks for including docs.

**Comment by lorefnon** [comment]
Thanks. Curious about the motivation for the rust rewrite ? Is it intended to improve performance for cases when the graphql schema changes very frequently and the codegen has to be run repeatedly ?

**Comment by timkendall** [comment]
@lorefnon Exactly.

**Pull request merged**
